name: Main workflow

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-sol:
    name: Foundry build n test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: aave-dao/action-rpc-env@main
        with:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

      - name: Run Foundry setup
        uses: aave-dao/github-workflows/.github/actions/foundry-setup@main

      - name: Run Forge tests
        id: test
        uses: aave-dao/github-workflows/.github/actions/foundry-test@main
        with:
          MODE: "CHANGED"
          FOUNDRY_PROFILE: "monad"

      - name: Run common unit tests
        id: unit_tests
        run: |
          forge test --match-path 'tests/unit-tests/*'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install JS dependencies
        run: pnpm install --frozen-lockfile

      - name: Run report JS tests
        run: pnpm run vitest

      - name: Run Forge tests
        uses: aave-dao/github-workflows/.github/actions/comment-artifact@main

      # we let failing tests pass so we can log them in the comment, still we want the ci to fail
      - name: Post test
        if: ${{ steps.test.outputs.testStatus != 0 || steps.unit_tests.outputs.testStatus != 0}}
        run: |
          echo "tests failed"
          exit 1
